package com.snowedunderproductions.graphprobe.jqwik.annotations;

import java.lang.annotation.*;

/**
 * Documents and references the arbitrary provider(s) used in a GraphQL property test.
 * <p>
 * This annotation is purely documentary: it makes the relationship between test parameters
 * and their {@code @Provide}-annotated supplier methods explicit at a glance.  The actual
 * binding is still performed by jqwik's {@link net.jqwik.api.ForAll @ForAll} and
 * {@link net.jqwik.api.Provide @Provide} annotations.  Apply this annotation at the method
 * level (alongside {@link GraphQLProperty @GraphQLProperty}) or at the parameter level to
 * record per-parameter metadata.
 * </p>
 * <p>
 * The {@link #source()} attribute uses the {@link DataSource} enum to categorise whether
 * values are generated by jqwik (e.g. via
 * {@link com.snowedunderproductions.graphprobe.jqwik.arbitraries.GraphQLArbitraries}),
 * sampled from the database via
 * {@link com.snowedunderproductions.graphprobe.jqwik.arbitraries.DatabaseArbitraryProvider},
 * loaded from CSV, or drawn from an external service.
 * </p>
 *
 * <h3>Single-provider example</h3>
 * <pre>{@code
 * @GraphQLProperty
 * @GraphQLArbitrary(
 *     provider    = "userIds",
 *     description = "Valid user IDs from the users table",
 *     source      = GraphQLArbitrary.DataSource.DATABASE
 * )
 * void testUserQuery(@ForAll("userIds") String userId) {
 *     GraphQLTestClient client = new GraphQLTestClient();
 *     String result = client.executeQuery(
 *         String.format("{ user(id: \"%s\") { name } }", userId),
 *         "$.data.user.name"
 *     );
 *     assertThat(result).isNotEmpty();
 * }
 *
 * @Provide
 * Arbitrary<String> userIds() {
 *     return DatabaseArbitraryProvider
 *         .fromQuery("SELECT user_id FROM users LIMIT 100")
 *         .extractString("user_id");
 * }
 * }</pre>
 *
 * <h3>Multi-provider example</h3>
 * <pre>{@code
 * @GraphQLProperty
 * @GraphQLArbitrary(
 *     provider    = {"userIds", "productIds"},
 *     description = "Test user and product ID combinations"
 * )
 * void testUserProductInteraction(
 *     @ForAll("userIds")    String userId,
 *     @ForAll("productIds") String productId
 * ) {
 *     // test implementation
 * }
 * }</pre>
 *
 * @see GraphQLProperty
 * @see net.jqwik.api.ForAll
 * @see net.jqwik.api.Provide
 * @see com.snowedunderproductions.graphprobe.jqwik.arbitraries.GraphQLArbitraries
 * @see com.snowedunderproductions.graphprobe.jqwik.arbitraries.DatabaseArbitraryProvider
 * @since 1.0.0
 */
@Target({ElementType.METHOD, ElementType.PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface GraphQLArbitrary {

    /**
     * Names of the {@code @Provide}-annotated methods that supply arbitraries for this test.
     * <p>
     * Each name must exactly match the corresponding {@link net.jqwik.api.Provide @Provide}
     * method name (or its explicit label).  For tests with multiple parameters, list every
     * provider in the same order as the parameters.
     * </p>
     *
     * @return provider method names; empty array when used solely for documentation
     */
    String[] provider() default {};

    /**
     * Human-readable description of what this arbitrary represents.
     * <p>
     * Use this to document the domain and constraints of the generated values.
     * </p>
     *
     * @return description of the arbitrary
     */
    String description() default "";

    /**
     * Expected domain of values (optional documentation).
     * <p>
     * Examples: "UUID strings", "integers 1-1000", "valid email addresses"
     * </p>
     *
     * @return the value domain description
     */
    String domain() default "";

    /**
     * Whether this arbitrary includes edge cases.
     * <p>
     * Document whether the arbitrary is configured to test boundary values.
     * </p>
     *
     * @return true if edge cases are included
     */
    boolean includesEdgeCases() default true;

    /**
     * Source type of the arbitrary data.
     *
     * @return the data source type
     */
    DataSource source() default DataSource.GENERATED;

    /**
     * Categorises the origin of the values produced by the arbitrary provider.
     * <p>
     * Use this to document whether generated values come from jqwik's built-in generators,
     * are sampled from a live database, loaded from a CSV file, or originate from some
     * other source.  The value has no effect on test execution; it is purely informational.
     * </p>
     */
    enum DataSource {
        /**
         * Data generated by jqwik arbitraries.
         */
        GENERATED,

        /**
         * Data sampled from database queries.
         */
        DATABASE,

        /**
         * Data loaded from CSV files.
         */
        CSV,

        /**
         * Data from external API or service.
         */
        EXTERNAL,

        /**
         * Mixed sources.
         */
        MIXED
    }
}
