/**
 * jqwik-specific annotations for property-based GraphQL API testing.
 *
 * <p>This package provides two complementary annotations that work alongside jqwik's
 * own {@link net.jqwik.api.ForAll} and {@link net.jqwik.api.Provide} annotations:
 *
 * <h3>Property test marker</h3>
 * <ul>
 *   <li>{@link com.snowedunderproductions.graphprobe.jqwik.annotations.GraphQLProperty} — a
 *       meta-annotation that composes jqwik's {@link net.jqwik.api.Property @Property} with
 *       GraphQL-specific semantics.  It exposes the most commonly tuned attributes
 *       ({@code tries}, {@code seed}, {@code shrinking}, {@code maxDiscardRatio},
 *       {@code generation}, {@code edgeCases}) so that consuming test classes do not need
 *       to import jqwik types directly for routine configuration.</li>
 * </ul>
 *
 * <h3>Arbitrary documentation</h3>
 * <ul>
 *   <li>{@link com.snowedunderproductions.graphprobe.jqwik.annotations.GraphQLArbitrary} — a
 *       purely documentary annotation that makes the relationship between a test parameter and
 *       its {@code @Provide}-annotated supplier method explicit.  It records the provider name(s),
 *       a human-readable description, the value domain, whether edge cases are included, and the
 *       {@link com.snowedunderproductions.graphprobe.jqwik.annotations.GraphQLArbitrary.DataSource}
 *       — i.e. whether values are generated by jqwik, sampled from the database, loaded from CSV,
 *       or drawn from an external service.</li>
 * </ul>
 *
 * <h3>Typical usage</h3>
 * <pre>{@code
 * @GraphQLProperty(tries = 50)
 * @GraphQLArbitrary(
 *     provider    = "userIds",
 *     description = "Valid user IDs from the users table",
 *     source      = GraphQLArbitrary.DataSource.DATABASE
 * )
 * void testUserQueryReturnsData(@ForAll("userIds") String userId) {
 *     GraphQLTestClient client = new GraphQLTestClient();
 *     String name = client.executeQuery(
 *         String.format("{ user(id: \"%s\") { name } }", userId),
 *         "$.data.user.name"
 *     );
 *     assertThat(name).isNotEmpty();
 * }
 *
 * @Provide
 * Arbitrary<String> userIds() {
 *     return DatabaseArbitraryProvider
 *         .fromQuery("SELECT user_id FROM users WHERE active = true LIMIT 100")
 *         .extractString("user_id");
 * }
 * }</pre>
 *
 * @see com.snowedunderproductions.graphprobe.jqwik.arbitraries.GraphQLArbitraries
 * @see com.snowedunderproductions.graphprobe.jqwik.arbitraries.GraphQLFuzzingArbitraries
 * @see com.snowedunderproductions.graphprobe.jqwik.arbitraries.DatabaseArbitraryProvider
 * @see com.snowedunderproductions.graphprobe.jqwik.providers.JqwikArgumentsProvider
 */
package com.snowedunderproductions.graphprobe.jqwik.annotations;
